# Generated by Django 5.2.4 on 2025-07-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monument_gallery/')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.monument')),
            ],
        ),
    ]
